/**
 * Family 2 — table / grille generator (after Rugg's Cardan grille).
 *
 * Rugg's hypothesis: words were produced by combining syllable fragments
 * from a prepared table (prefix + core + suffix columns) through a moving
 * grille. Our parametrized abstraction: slot inventories are extracted
 * from the WORKING corpus with a fixed crude segmentation (first glyphs /
 * middle / last glyphs), then words are generated by drawing one fragment
 * per slot, weighted by frequency. The "grille movement" is abstracted as
 * stickiness: the probability that the next word reuses a fragment of the
 * previous one (adjacent table cells share fragments).
 *
 * Fixed segmentation rule (not a parameter, deliberately crude):
 *   length 1-3: core only;  length >= 4: prefix = first 2 glyphs,
 *   suffix = last 2 glyphs, core = the middle (possibly empty).
 */
import { type Rng, weightedPicker } from "../corpus/random.ts";
import { splitGlyphs } from "../corpus/tokenize.ts";
import { positionalGlyphCounts, positionalPickers } from "./positional.ts";
import type { GeneratorContext, GeneratorFamily, Params } from "./types.ts";

export interface Inventories {
  prefixes: (rng: Rng) => string;
  cores: (rng: Rng) => string;
  suffixes: (rng: Rng) => string;
}

function topPicker(counts: Map<string, number>, k: number): (rng: Rng) => string {
  const top = [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  return weightedPicker(top.slice(0, Math.max(1, k)));
}

export function buildInventories(
  words: readonly string[],
  prefixCount: number,
  coreCount: number,
  suffixCount: number,
): Inventories {
  const prefixes = new Map<string, number>();
  const cores = new Map<string, number>();
  const suffixes = new Map<string, number>();
  const bump = (m: Map<string, number>, key: string) => {
    if (key !== "") m.set(key, (m.get(key) ?? 0) + 1);
  };
  for (const word of words) {
    const g = splitGlyphs(word);
    if (g.length <= 3) {
      bump(cores, g.join(""));
    } else {
      bump(prefixes, g.slice(0, 2).join(""));
      bump(cores, g.slice(2, -2).join(""));
      bump(suffixes, g.slice(-2).join(""));
    }
  }
  return {
    prefixes: topPicker(prefixes, prefixCount),
    cores: topPicker(cores, coreCount),
    suffixes: topPicker(suffixes, suffixCount),
  };
}

/**
 * Synthetic inventories: fragments are INVENTED from positional glyph
 * distributions instead of harvested from real words. Same slot sizes as
 * the crude segmentation (prefix 2 glyphs, suffix 2 glyphs, core 1-3).
 * This levels the information asymmetry flagged in the first T3 report:
 * a table built this way knows the glyph histograms per position, but has
 * never seen an actual Voynich word.
 */
export function buildSyntheticInventories(
  words: readonly string[],
  prefixCount: number,
  coreCount: number,
  suffixCount: number,
  rng: Rng,
): Inventories {
  const pickers = positionalPickers(positionalGlyphCounts(words));
  const fragments = (count: number, make: () => string): ((rng: Rng) => string) => {
    // Draw distinct fragments; weight by draw order (earlier = heavier),
    // a crude Zipf-like weighting so inventories have frequent and rare cells.
    const seen = new Map<string, number>();
    let attempts = 0;
    while (seen.size < count && attempts < count * 30) {
      const fragment = make();
      attempts++;
      if (fragment !== "" && !seen.has(fragment)) seen.set(fragment, count - seen.size);
    }
    return weightedPicker([...seen.entries()]);
  };
  return {
    prefixes: fragments(prefixCount, () => pickers.initial(rng) + pickers.medial(rng)),
    cores: fragments(coreCount, () => {
      const len = 1 + Math.floor(rng() * 3);
      let core = "";
      for (let i = 0; i < len; i++) core += pickers.medial(rng);
      return core;
    }),
    suffixes: fragments(suffixCount, () => pickers.medial(rng) + pickers.final(rng)),
  };
}

export const tableFamily: GeneratorFamily = {
  name: "Table/grille",
  description:
    "words assembled as prefix+core+suffix from real or synthetic inventories (after Rugg); parameters: inventory source, sizes, empty slots, stickiness",
  paramSpace: {
    inventorySource: ["realFragments", "synthetic"],
    prefixCount: [12, 30, 60],
    coreCount: [40, 120],
    suffixCount: [12, 30, 60],
    pDropPrefix: [0.15, 0.35],
    pDropSuffix: [0.1, 0.3],
    stickiness: [0, 0.4],
  },
  generate(params: Params, ctx: GeneratorContext, rng: Rng): string[] {
    const inv =
      params.inventorySource === "synthetic"
        ? buildSyntheticInventories(
            ctx.voynichWords,
            params.prefixCount as number,
            params.coreCount as number,
            params.suffixCount as number,
            rng,
          )
        : buildInventories(
            ctx.voynichWords,
            params.prefixCount as number,
            params.coreCount as number,
            params.suffixCount as number,
          );
    const pDropPrefix = params.pDropPrefix as number;
    const pDropSuffix = params.pDropSuffix as number;
    const stickiness = params.stickiness as number;

    const words: string[] = [];
    let prevPrefix = "";
    let prevSuffix = "";
    for (let i = 0; i < ctx.tokenCount; i++) {
      const prefix =
        rng() < pDropPrefix
          ? ""
          : prevPrefix !== "" && rng() < stickiness
            ? prevPrefix
            : inv.prefixes(rng);
      const suffix =
        rng() < pDropSuffix
          ? ""
          : prevSuffix !== "" && rng() < stickiness
            ? prevSuffix
            : inv.suffixes(rng);
      const core = inv.cores(rng);
      words.push(prefix + core + suffix);
      prevPrefix = prefix;
      prevSuffix = suffix;
    }
    return words;
  },
};
