/**
 * CLI: generate the T2 control-corpora report.
 *
 * Usage:
 *   bun run controls:report
 *
 * Builds the five control corpora (real Latin, enciphered Latin, shuffled
 * Voynich, frequency-matched gibberish, self-citation), pours each into the
 * layout skeleton of the working corpus (same line structure, same token
 * count), runs the exact T1 battery on all of them, and reports per-metric
 * and aggregate distances to the Voynich signature. Generated artifact
 * (VOY-DOC-06); prose in English.
 */
import { buildControls } from "../controls/build.ts";
import { loadParagraphLines } from "../corpus/corpus.ts";
import { DEFAULT_DB_PATH, openDb } from "../ingest/db.ts";
import { CONTROLS, SIGNATURE } from "../policy.ts";
import { computeSignature, type Signature } from "../stats/signature.ts";
import { signatureDistances } from "../verify/distance.ts";

const REPORT_PATH = "reports/controls.md";

// --- Load the working corpus, build the five controls ------------------------

const db = openDb(DEFAULT_DB_PATH);
const meta = Object.fromEntries(
  (db.prepare("SELECT key, value FROM ingest_meta").all() as { key: string; value: string }[]).map(
    (r) => [r.key, r.value],
  ),
);
const voynichLines = loadParagraphLines(db);
db.close();

const { controls, skeleton, latinEntries } = await buildControls(voynichLines);

const corpora: { name: string; signature: Signature }[] = controls.map((c) => ({
  name: c.name,
  signature: computeSignature(c.lines, SIGNATURE),
}));
const reference = { name: "Voynich", signature: computeSignature(voynichLines, SIGNATURE) };

const result = signatureDistances(reference, corpora);

// --- Render ------------------------------------------------------------------

const f = (n: number, d = 3) => n.toFixed(d);
const int = (n: number) => n.toLocaleString("en-US");
const names = [reference.name, ...corpora.map((c) => c.name)];

const valueRows = result.rows
  .map((row) => `| ${row.metric} | ${names.map((n) => f(row.values[n] as number)).join(" | ")} |`)
  .join("\n");

const distanceRows = result.rows
  .map(
    (row) =>
      `| ${row.metric} | ${corpora.map((c) => f(row.distances[c.name] as number, 2)).join(" | ")} |`,
  )
  .join("\n");

const ranking = [...corpora]
  .map((c) => ({ name: c.name, d: result.aggregate[c.name] as number }))
  .sort((a, b) => a.d - b.d);

const report = `# Control Corpora - T2 Report

> Report generated by \`bun run controls:report\` on ${new Date().toISOString()} (VOY-DOC-06: do not edit by hand).
>
> Reference: Voynich working corpus (held-out excluded, VOY-DOC-03), paragraph
> text, source \`${meta.source_path}\` SHA-256 \`${meta.source_sha256}\`.
> Latin: Clementine Vulgate, ${latinEntries.map((e) => `\`${e.path}\``).join(" + ")} (registered, VOY-DOC-08).
> Seeds: cipher ${CONTROLS.cipherSeed}, shuffle ${CONTROLS.shuffleSeed}, gibberish ${CONTROLS.gibberishSeed}, self-citation ${CONTROLS.selfCitationSeed}.
> Self-citation: ${CONTROLS.selfCitation.seedWordCount} seed words, p(edit) ${CONTROLS.selfCitation.editProb}, p(2nd edit) ${CONTROLS.selfCitation.secondEditProb}.

**Purpose.** Learn what "nothing" looks like: each control embodies a trivial
explanation (it is Latin, it is a simple cipher, it is chance, etc.), and the T1
battery measures what it reproduces or fails to reproduce from the Voynich
signature. This is mandatory before interpretation (VOY-DOC-02).

**Equalization method.** The six corpora share the same layout skeleton:
${int(skeleton.lines.length)} lines, the same number of words per line, the same
paragraph starts, and therefore exactly ${int(skeleton.tokenCount)} tokens each.
Size-sensitive measures (entropies, MATTR, hapax) are compared at strictly equal
size with the same estimator, which is the validity condition set in T1.

The five controls:

1. **Latin** - Clementine Vulgate (Genesis + Exodus), real medieval text: what a
   real language looks like in our battery.
2. **Enciphered Latin** - the same text under seeded monoalphabetic substitution:
   what a simple cipher changes (symbol identity) and does not change (everything
   else).
3. **Shuffled Voynich** - real manuscript words in random order: destroys
   sequential structure, keeps the lexicon.
4. **Gibberish** - glyphs drawn i.i.d. from real frequencies, with real word
   lengths: only the histogram remains.
5. **Self-citation** - each word is a mutated copy of an already written word
   (after Timm & Schinner): the "meaningless mechanical text" hypothesis embodied.

> **Pedagogy - z-score.** To compare measures with different units (bits,
> percentages, slopes), each value is expressed as "number of standard deviations
> above/below the group mean": that is the z-score. A control's distance to
> Voynichese on one metric is |z(control) - z(Voynich)|. The aggregate distance is
> the unweighted mean over the ${result.metricCount} metrics: the simplest
> possible choice, stated and documented.

> **VOY-DOC-07 - multiple comparisons.** ${result.metricCount} metrics x ${corpora.length} controls =
> ${result.metricCount * corpora.length} comparisons. Isolated coincidences are expected; only coherent
> family-level patterns count.

## 1. Ranking by Aggregate Distance

| Rank | Corpus | Aggregate distance to Voynichese |
| ---: | --- | ---: |
${ranking.map((r, i) => `| ${i + 1} | ${r.name} | ${f(r.d, 3)} |`).join("\n")}

## 2. Raw Values (Same T1 Battery Everywhere)

| Metric | ${names.join(" | ")} |
| --- | ${names.map(() => "---:").join(" | ")} |
${valueRows}

Eva-specific metrics (\`q\` behavior, gallows) are excluded from the distance vector:
they have no meaning for Latin. They remain in the T1 report.

## 3. Per-Metric Distances (|Delta z| to Voynichese)

| Metric | ${corpora.map((c) => c.name).join(" | ")} |
| --- | ${corpora.map(() => "---:").join(" | ")} |
${distanceRows}
| **Aggregate (mean)** | ${corpora.map((c) => `**${f(result.aggregate[c.name] as number, 3)}**`).join(" | ")} |

## 4. What Each Control Teaches

Metric-by-metric reading of table 3, family by family:

- **Real Latin:** natural language has much higher h2, more varied word lengths,
  and fewer adjacent repetitions. Any Voynich/control gap here is a gap to "a real
  European language laid out the same way".
- **Enciphered Latin:** compare its column with clear Latin: distances are almost
  identical metric by metric. **This is T2's key lesson**: a substitution cipher
  moves no structural statistic (h1, h2, Zipf, lengths, repetitions). If
  Voynichese were a simple cipher of a European language, it would have that
  language's statistics. It does not.
- **Shuffled Voynich:** by construction, preserves everything that depends only on
  the lexicon (Zipf, lengths, hapax, MATTR, h1). What degrades under shuffling
  (adjacent repetitions, neighbour similarity, line effects, inter-word h2) is
  precisely the *sequential* part of the signature, the part a language or ordered
  procedure must explain.
- **Gibberish:** preserves only h1 (imposed histogram) and word lengths (the real
  length sequence is kept position by position, so "line effects" at 0.00 in table
  3 are construction artifacts, not chance succeeding). Everything else collapses:
  h2 rises toward h1 (without bigram structure, the previous glyph teaches
  nothing), Zipf slope flattens, vocabulary explodes (MATTR, hapax). Useful for
  seeing what "well-dressed randomness" does NOT do.
- **Self-citation:** with naive fixed parameters, inspect what it brings closer
  (repetitions, neighbour similarity, lengths) and what it still misses. T3 will
  search this family's parameter space.

**Interpretation guardrail (VOY-DOC-01/02).** This table ranks *families of
trivial explanations*, not truths: a low distance says "this family reproduces
these properties", never "the manuscript was produced this way".
`;

await Bun.write(REPORT_PATH, report);
console.log(`Report written to ${REPORT_PATH}`);
console.log("aggregate distances:");
for (const r of ranking) console.log(`  ${r.name}: ${f(r.d, 3)}`);
