/**
 * CLI: generate the corpus inventory report (T0 exit criterion).
 *
 * Usage:
 *   bun run corpus:report
 *
 * Reads data/db/voynich.sqlite and writes reports/inventory.md. The report
 * is a generated artifact (VOY-DOC-06): never edit it by hand; re-run this
 * command instead. Report prose is in English; the
 * pedagogical notes are part of the deliverable.
 */
import type { Database } from "bun:sqlite";
import { DEFAULT_DB_PATH, openDb } from "../ingest/db.ts";
import { SANITY } from "../policy.ts";

const REPORT_PATH = "reports/inventory.md";

const SECTION_LABELS: Record<string, string> = {
  H: "Herbal",
  A: "Astronomical",
  C: "Cosmological",
  B: "Biological/balneological",
  P: "Pharmaceutical",
  S: "Marginal stars (recipes)",
  T: "Text only",
  Z: "Zodiac",
};

function one<T>(db: Database, sql: string): T {
  return db.prepare(sql).get() as T;
}
function all<T>(db: Database, sql: string): T[] {
  return db.prepare(sql).all() as T[];
}

const db = openDb(DEFAULT_DB_PATH);

const meta = Object.fromEntries(
  all<{ key: string; value: string }>(db, "SELECT key, value FROM ingest_meta").map((r) => [
    r.key,
    r.value,
  ]),
);

const counts = {
  pages: one<{ n: number }>(db, "SELECT count(*) n FROM pages").n,
  loci: one<{ n: number }>(db, "SELECT count(*) n FROM loci").n,
  tokens: one<{ n: number }>(db, "SELECT count(*) n FROM tokens").n,
  glyphs: one<{ n: number }>(db, "SELECT coalesce(sum(glyph_count),0) n FROM tokens").n,
};

const sanityRows = (
  [
    ["Pages", counts.pages, SANITY.pages],
    ["Loci", counts.loci, SANITY.loci],
    ["Tokens", counts.tokens, SANITY.tokens],
    ["Glyphs", counts.glyphs, SANITY.glyphs],
  ] as const
).map(([label, value, range]) => {
  const ok = value >= range.min && value <= range.max;
  return `| ${label} | ${value.toLocaleString("en-US")} | ${range.min.toLocaleString("en-US")} - ${range.max.toLocaleString("en-US")} | ${ok ? "ok" : "OUT OF RANGE"} |`;
});

const sections = all<{ s: string | null; lang: string | null; n: number }>(
  db,
  `SELECT illustration_type s, currier_language lang, count(*) n
   FROM pages GROUP BY illustration_type, currier_language
   ORDER BY illustration_type, currier_language`,
);
const sectionNames = [...new Set(sections.map((r) => r.s ?? "?"))].sort();
const crossTab = sectionNames.map((s) => {
  const row = (lang: string | null) =>
    sections.find((r) => (r.s ?? "?") === s && r.lang === lang)?.n ?? 0;
  const unset = sections
    .filter((r) => (r.s ?? "?") === s && r.lang !== "A" && r.lang !== "B")
    .reduce((acc, r) => acc + r.n, 0);
  const total = row("A") + row("B") + unset;
  return `| ${SECTION_LABELS[s] ?? s} (${s}) | ${row("A")} | ${row("B")} | ${unset} | ${total} |`;
});

const hands = all<{ hand: string | null; n: number }>(
  db,
  "SELECT hand, count(*) n FROM pages GROUP BY hand ORDER BY hand",
);

const topTokens = all<{ form: string; n: number }>(
  db,
  `SELECT form, count(*) n FROM working_tokens
   WHERE has_unreadable = 0
   GROUP BY form ORDER BY n DESC, form LIMIT ${SANITY.topTokenCount}`,
);
const topForms = new Set(topTokens.map((t) => t.form));
const expectedChecks = SANITY.expectedTopTokens.map(
  (f) => `\`${f}\` ${topForms.has(f) ? "present" : "ABSENT (probable tokenization bug)"}`,
);

const holdout = {
  pages: one<{ n: number }>(db, "SELECT count(*) n FROM holdout_pages").n,
  folios: all<{ folio: string }>(db, "SELECT DISTINCT folio FROM holdout_pages ORDER BY folio"),
  info: one<{ seed: number | null; frozen_at: string | null }>(
    db,
    "SELECT min(seed) seed, min(frozen_at) frozen_at FROM holdout_pages",
  ),
  workingTokens: one<{ n: number }>(db, "SELECT count(*) n FROM working_tokens").n,
};

const uncertain = {
  alternatives: one<{ n: number }>(db, "SELECT count(*) n FROM tokens WHERE has_alternative=1").n,
  ligatures: one<{ n: number }>(db, "SELECT count(*) n FROM tokens WHERE has_ligature=1").n,
  highAscii: one<{ n: number }>(db, "SELECT count(*) n FROM tokens WHERE has_high_ascii=1").n,
  unreadable: one<{ n: number }>(db, "SELECT count(*) n FROM tokens WHERE has_unreadable=1").n,
  commaSep: one<{ n: number }>(db, "SELECT count(*) n FROM tokens WHERE sep_before=','").n,
};

const types = one<{ n: number }>(
  db,
  "SELECT count(DISTINCT form) n FROM working_tokens WHERE has_unreadable=0",
).n;

const report = `# Corpus Inventory - T0 Report

> Report generated by \`bun run corpus:report\` on ${new Date().toISOString()} (VOY-DOC-06: do not edit by hand).
>
> Source: \`${meta.source_path}\` (IVTFF ${meta.ivtff_version}, alphabet ${meta.ivtff_alphabet})
> SHA-256 : \`${meta.source_sha256}\`
> Ingested: ${meta.ingested_at}, tokenization policy: \`${meta.tokenize_config}\`

## 1. Global Counts and Sanity Checks

Expected ranges come from the plan (section 1.3) and the literature. A count outside
range signals a parser bug before any other interpretation.

| Measure | Value | Expected range | Verdict |
| --- | ---: | ---: | :---: |
${sanityRows.join("\n")}

**Vocabulary**: ${types.toLocaleString("en-US")} distinct forms (working corpus, readable tokens).

> **Pedagogy - token vs type.** A *token* is one occurrence of a word in the text;
> a *type* is a distinct form. \`daiin daiin ol\` contains 3 tokens but 2 types.
> The type/token relation later gives a measure of vocabulary richness (T1).

> **Note on glyph counting.** Our glyph unit is one EVA character, an \`@nnn;\`
> sequence (extended glyph), or a \`?\` (unreadable). The literature's "~170,000"
> depends on different conventions (digraphs \`ch\`/\`sh\` counted as one glyph,
> labels excluded, etc.). Fine comparison happens in T1; here we only check the
> order of magnitude.

## 2. Pages by Section and Currier Language

> **Pedagogy - Currier languages.** In the 1970s, Prescott Currier observed that
> the pages split into two statistical "dialects", A and B: the same glyphs, but
> clearly different vocabularies and frequencies. This is not a "language" in the
> linguistic sense; it is a robust statistical fact that T1 rechecks.

| Section | Currier A | Currier B | Unmarked | Total |
| --- | ---: | ---: | ---: | ---: |
${crossTab.join("\n")}

Scribe hands (Lisa Fagin Davis identification, variable \`$H\`):
${hands.map((h) => `hand ${h.hand ?? "?"}: ${h.n} pages`).join(" · ")}.
The page marked \`@\` is folio f115r, where the hand changes within the page
(text tags \`<@H=2>\` / \`<@H=3>\` applied line by line).

## 3. The ${SANITY.topTokenCount} Most Frequent Tokens (Working Corpus)

Expected check: ${expectedChecks.join(", ")}.

| Rank | Form | Occurrences |
| ---: | --- | ---: |
${topTokens.map((t, i) => `| ${i + 1} | \`${t.form}\` | ${t.n} |`).join("\n")}

## 4. Transliteration Uncertainties (Tracked per Token)

| Type | Affected tokens |
| --- | ---: |
| Alternative reading \`[a:o]\` (first option kept) | ${uncertain.alternatives} |
| Ligature \`{...}\` (braces removed, content kept) | ${uncertain.ligatures} |
| Extended glyph \`@nnn;\` (kept as an atomic unit) | ${uncertain.highAscii} |
| Unreadable glyph \`?\` (token excluded from frequencies) | ${uncertain.unreadable} |
| Uncertain space \`,\` before token (treated as separator) | ${uncertain.commaSep} |

Handling uncertain spaces is an **analysis parameter** (default policy: separator,
like \`.\`). Every token records its previous separator, so the impact of this
choice remains measurable.

## 5. Frozen Held-Out (VOY-DOC-03)

> **Pedagogy - why a held-out?** If we adjust methods and thresholds on the whole
> corpus, we eventually "learn" its quirks by heart: everything looks like it
> works because we optimized on it. We therefore freeze a part of the corpus that
> no tuning may touch. It is used only for final evaluations, like an exam whose
> questions nobody has seen.

- Deterministic draw, **seed ${holdout.info.seed}** (= Beinecke MS 408 shelfmark), frozen on ${holdout.info.frozen_at}.
- Stratified by section x Currier language; drawn by **whole folio** (recto and
  verso together, to avoid leakage between both sides of a leaf).
- **${holdout.folios.length} folios** (${holdout.pages} pages) frozen: ${holdout.folios.map((f) => f.folio).join(", ")}.
- Remaining working corpus: ${holdout.workingTokens.toLocaleString("en-US")} tokens out of ${counts.tokens.toLocaleString("en-US")}.
- Durable list committed in \`data/holdout.json\`; \`bun run holdout:freeze\`
  verifies on every run that the draw reproduces exactly this list and refuses
  otherwise.

The SQL views \`working_pages\` / \`working_loci\` / \`working_tokens\` exclude these
pages. Standard analyses must query only these views. Full tables are reserved for
final phase evaluations (\`--final-eval\`).
`;

await Bun.write(REPORT_PATH, report);
console.log(`Report written to ${REPORT_PATH}`);
db.close();
