/**
 * CLI: generate the project-wide synthesis report.
 *
 * Usage:
 *   bun run synthesis:report
 *
 * One narrative document tying T0..T5 + diagnostics together. T0-T2 numbers
 * are RECOMPUTED live; the T3 ranking/frontier and the robustness verdict
 * are PARSED from their canonical reports (reports/hypotheses.md,
 * reports/transliteration-robustness.md). The T3/T5 closure narrative
 * mirrors VOYNICH-LAB-PLAN.md section 6 (the canonical source); the T5
 * conclusions summarize reports/structure.md. Regenerating the upstream
 * reports then this one refreshes everything (VOY-DOC-06).
 */
import { buildControls } from "../controls/build.ts";
import { loadParagraphLines } from "../corpus/corpus.ts";
import { DEFAULT_DB_PATH, openDb } from "../ingest/db.ts";
import { EXPECTED_SIGNATURE, SEARCH, SIGNATURE } from "../policy.ts";
import { computeSignature } from "../stats/signature.ts";
import { signatureDistances } from "../verify/distance.ts";

const REPORT_PATH = "reports/synthesis.md";

const f = (n: number, d = 3) => n.toFixed(d);
const pct = (n: number, d = 1) => `${(100 * n).toFixed(d)}%`;
const int = (n: number) => n.toLocaleString("en-US");

// --- Live recomputation: T0 inventory, T1 signature, T2 distances -------------

const db = openDb(DEFAULT_DB_PATH);
const meta = Object.fromEntries(
  (db.prepare("SELECT key, value FROM ingest_meta").all() as { key: string; value: string }[]).map(
    (r) => [r.key, r.value],
  ),
);
const counts = {
  pages: (db.prepare("SELECT count(*) n FROM pages").get() as { n: number }).n,
  loci: (db.prepare("SELECT count(*) n FROM loci").get() as { n: number }).n,
  tokens: (db.prepare("SELECT count(*) n FROM tokens").get() as { n: number }).n,
  holdoutPages: (db.prepare("SELECT count(*) n FROM holdout_pages").get() as { n: number }).n,
};
const workingLines = loadParagraphLines(db);
const linesA = loadParagraphLines(db, { language: "A" });
const linesB = loadParagraphLines(db, { language: "B" });
db.close();

const holdout = (await Bun.file("data/holdout.json").json()) as {
  seed: number;
  frozenAt: string;
  folios: string[];
};

const sig = computeSignature(workingLines, SIGNATURE);
const sigA = computeSignature(linesA, SIGNATURE);
const sigB = computeSignature(linesB, SIGNATURE);

const E = EXPECTED_SIGNATURE;
const gallowsContrast =
  sig.morphology.gallowsOtherShare === 0
    ? Number.POSITIVE_INFINITY
    : sig.morphology.gallowsParStartShare / sig.morphology.gallowsOtherShare;
const calibrationChecks: boolean[] = [
  sig.entropy.h2 <= E.h2Max,
  sig.zipf.slope >= E.zipfSlope.min && sig.zipf.slope <= E.zipfSlope.max,
  sig.wordLength.mode >= E.wordLengthMode.min && sig.wordLength.mode <= E.wordLengthMode.max,
  sig.wordLength.sd <= E.wordLengthSdMax,
  sig.morphology.qInitialShare >= E.qInitialShareMin,
  sig.morphology.qFollowedByO >= E.qFollowedByOMin,
  gallowsContrast >= E.gallowsContrastMin,
];
const calibrationPassed = calibrationChecks.filter(Boolean).length;

const { controls } = await buildControls(workingLines);
const t2 = signatureDistances(
  { name: "Voynich", signature: sig },
  controls.map((c) => ({ name: c.name, signature: computeSignature(c.lines, SIGNATURE) })),
);
const t2Ranking = controls
  .map((c) => ({ name: c.name, d: t2.aggregate[c.name] as number }))
  .sort((a, b) => a.d - b.d);

// --- Parse canonical reports for T3 and robustness ----------------------------

async function parseTable(path: string, sectionStart: string): Promise<string[]> {
  const text = await Bun.file(path).text();
  const start = text.indexOf(sectionStart);
  if (start < 0) throw new Error(`section ${JSON.stringify(sectionStart)} not found in ${path}`);
  const lines = text.slice(start).split("\n");
  const rows: string[] = [];
  let inTable = false;
  for (const line of lines.slice(1)) {
    if (line.startsWith("|")) {
      inTable = true;
      rows.push(line);
    } else if (inTable) {
      break;
    }
  }
  return rows;
}

const t3RankingRows = (await parseTable("reports/hypotheses.md", "## 1.")).slice(2);
const t3FrontierRows = (await parseTable("reports/hypotheses.md", "## 4.")).slice(2);

const robustnessText = await Bun.file("reports/transliteration-robustness.md").text();
const robustnessMatch = robustnessText.match(
  /\*\*(?:All (\d+) vector metrics are robust|(\d+)\/(\d+) metrics diverge)\*\*/,
);
const robustnessLine = robustnessMatch
  ? robustnessMatch[0].replaceAll("**", "")
  : "see reports/transliteration-robustness.md";

// --- Render --------------------------------------------------------------------

const report = `# General Synthesis of the Voynich Lab Project

> Report generated by \`bun run synthesis:report\` on ${new Date().toISOString()} (VOY-DOC-06: do not edit by hand).
>
> T0-T2 numbers recomputed live; T3 ranking and robustness verdict read from
> their canonical reports (\`reports/hypotheses.md\`,
> \`reports/transliteration-robustness.md\`), themselves regenerable. The
> T3/T5 closure narrative mirrors \`VOYNICH-LAB-PLAN.md\` section 6.
> Source: \`${meta.source_path}\`, SHA-256 \`${meta.source_sha256}\`.

## 1. What This Project Is, and Is Not

A statistical-analysis laboratory for the Voynich manuscript (Beinecke MS 408)
that (a) reproduces the text's known statistical signature, (b) implements
hypothesis families as text generators, and (c) ranks them by measured fidelity to
that signature against control corpora. **It translates nothing and claims no
meaning** (VOY-DOC-01): its verdicts are distances, rankings, and exclusions,
including negative results documented at the same level as positive ones
(VOY-DOC-05).

## 2. T0 - The Corpus

- ZL transliteration (Zandbergen-Landini), IVTFF ${meta.ivtff_version}, EVA
  alphabet, registered with hash and license (VOY-DOC-08): ${int(counts.pages)}
  pages, ${int(counts.loci)} loci, ${int(counts.tokens)} tokens, consistent with
  published orders of magnitude.
- **Held-out frozen from T0** (VOY-DOC-03): ${holdout.folios.length} folios
  (${int(counts.holdoutPages)} pages), deterministic draw seed ${holdout.seed},
  stratified by section x Currier language, frozen on ${holdout.frozenAt.slice(0, 10)},
  durable list committed. Standard analyses see only the \`working_*\` views; the
  held-out has served only final phase evaluations, logged in
  \`reports/hypotheses.md\`.
- Working corpus for analyses: paragraph text, ${int(sig.tokens)} tokens.

## 3. T1 - The Signature, Rechecked by Our Instruments

${calibrationPassed}/${calibrationChecks.length} calibration checks pass against the literature
(details: \`reports/signature.md\`). Key numbers, recomputed now:

| Measure | Value | What it says |
| --- | ---: | --- |
| h2 (conditional entropy) | ${f(sig.entropy.h2)} bits | unusually predictable text (European languages: 3-3.5) |
| Zipf slope | ${f(sig.zipf.slope)} (r² ${f(sig.zipf.r2)}) | language-like frequency distribution |
| Word lengths | mode ${sig.wordLength.mode}, sd ${f(sig.wordLength.sd, 2)} | narrow, almost binomial: unusual |
| Initial \`q\` / P(o\\|q) | ${pct(sig.morphology.qInitialShare)} / ${pct(sig.morphology.qFollowedByO)} | near-mandatory glyph positions |
| Gallows at paragraph start | ${pct(sig.morphology.gallowsParStartShare)} vs ${pct(sig.morphology.gallowsOtherShare)} | contrast ${f(gallowsContrast, 1)}x |
| First/last line word | ${f(sig.lineEffects.firstMean, 2)} / ${f(sig.lineEffects.lastMean, 2)} glyphs (inner ${f(sig.lineEffects.innerMean, 2)}) | the line is a functional unit |
| Adjacent repetitions | ${pct(sig.repetition.identicalRate, 2)} identical, ${pct(sig.repetition.distance1Rate, 2)} at distance 1 | the core of the self-citation hypothesis |
| Currier A != B | h2 ${f(sigA.entropy.h2)} vs ${f(sigB.entropy.h2)} | almost two corpora (${int(sigA.tokens)} vs ${int(sigB.tokens)} tokens) |

## 4. T2 - Controls: What "Nothing" Looks Like

Six corpora with the same layout skeleton (${int(sig.tokens)} tokens each), one
battery. Aggregate distance to Voynichese (group z-scores, ${t2.metricCount} metrics):

| Rank | Control | Distance |
| ---: | --- | ---: |
${t2Ranking.map((r, i) => `| ${i + 1} | ${r.name} | ${f(r.d)} |`).join("\n")}

Central lesson, proven by measurement: clear Latin and Latin under
monoalphabetic substitution have **identical metric-by-metric distances**. A
simple cipher moves no structural statistic. If Voynichese were a simple cipher of
a European language, it would have that language's statistics. It does not. This
is the project's strongest exclusion.

## 5. T3 - Hypothesis Families Ranked on the Final Exam (Phase Closed)

Each family is a parameterized generator; tuning on the working corpus (scores
averaged over ${SEARCH.scoreReplicates} generations), evaluation on held-out.
**Phase T3 is declared closed** (plan section 6.2): the residual frontier is at
the instrument's resolution limit. Final ranking (copied from
\`reports/hypotheses.md\`, which is authoritative and includes the evaluation log):

| Rank | Family | Working distance (+/-sd) | Held-out distance (+/-sd) | Delta |
| ---: | --- | ---: | ---: | ---: |
${t3RankingRows.map((r) => r).join("\n")}

The leading family, **structured self-citation**, embodies: copying from the
lines above (Timm & Schinner), slot-replacement mutations (prefix/core/suffix),
and a small closed lexicon of "function words" weighted by 1/rank. Each ingredient
was validated by a dedicated diagnostic on the working corpus:

- \`reports/diag-selfcitation.md\`: local copying fails under random edits
  (length drift, over-similarity). The edit model was guilty, not locality.
  Major methodological fallout: single-draw scoring rewarded seed luck, so every
  score is now averaged.
- \`reports/diag-zipf.md\`: exact reuse (Simon process) repairs the Zipf slope but
  starves hapax; head and tail are coupled in this mechanism. Documented
  structural negative.
- \`reports/diag-lexicon.md\`: the closed lexicon decouples: Zipf AND hapax are held
  together for the first time, and global reuse becomes unnecessary
  (\`pGlobalReuse=0\` for all winners).

What no family still reproduces (conservative definition: best *aggregate*
candidate of each family; copied from \`reports/hypotheses.md\`):

| Metric | Best family | Normalized gap |
| --- | --- | ---: |
${t3FrontierRows.map((r) => r).join("\n")}

Dialect split (\`reports/hypotheses-ab.md\`): language-specific tuning gain is weak
and rankings do not move, but the frontier differs; on Currier A it almost
dissolves.

## 6. Robustness

- **Transliteration:** battery rerun on Takahashi's independent transliteration
  (IT): ${robustnessLine} (\`reports/transliteration-robustness.md\`). Only the
  "last word of line" effect depends on the transcriber; the rest describes the
  manuscript.
- **Generation noise:** scores averaged over ${SEARCH.scoreReplicates} seeds, with
  standard deviations displayed, since a diagnostic showed that a single draw
  could invert a ranking.

## 7. T5 - Structure Above the Line: Is There a Message? (Phase Closed)

The four planned measures converge (\`reports/structure.md\`), and the central
result is a **bracketing**, not a proof. At matched distance, vocabulary contrast
by section (flat with distance) and paragraph cohesion exceed every content-free
writing drift tested - folio order, writing campaigns by section or by hand - but
stay below a deliberate, complete redraw of word stocks per section/paragraph: a
content-free mechanism covers the observed value. The most directly referential
test - do **labels** behave like names of their drawings? - is negative: their
co-occurrence with their own page's text sits inside the stratified-permutation
null (p about 0.27). Paragraph-edge habits (gallows, longer first line) are real
but mechanical.

**Conclusion (VOY-DOC-01/05):** nothing above the line REQUIRES semantics. This is
not proof that the text is meaningless - it shifts the burden of proof: any content
claim must now explain why meaning left none of the traces we looked for. The
remaining frontier is external (section 9): meaning lives between a text and a
world, never inside the text alone.

## 8. What We Know, What We Do Not Know

**Established (with reports):**
1. The manuscript's published signature is reproduced by our instruments and is
   robust to a transcriber change.
2. The "simple substitution over a European language" family is excluded by
   measurement.
3. The abjad (vowel-stripped Latin) and Naibbe-style verbose cipher, as
   implemented, generalize poorly (overfitting measured on held-out).
4. A meaningless mechanical process, structured local copying plus closed lexicon,
   is the family most compatible with the measured signature.
5. Above the line (T5), section/paragraph vocabulary organization is bracketed by
   content-free mechanisms and labels are non-referential: nothing there requires
   a message either.

**Honest limits:**
1. "Compatible" does not mean "this is how the manuscript was produced"
   (VOY-DOC-01); a ranking is not a historical demonstration.
2. The leading family consumes real corpus fragments (documented information
   asymmetry; its synthetic variants remain the best at equal information, but
   farther away).
3. Fine line effects and the residual frontier remain unreproduced.
4. The held-out (${int(counts.holdoutPages)} pages) is small: final evaluations are
   noisy (sd displayed) and deliberately few (log kept).
5. T5 is a bracketing, not a disproof of meaning: a partial stock variation - still
   content-free - covers the observed structure. Only external anchoring (T6) could
   go further.

## 9. Open Leads (T6 - Not Started)

Both completed phases are closed (T3 and T5; plan section 6). The single
unexplored question is **external anchoring**: does the text covary with the
drawings? - the only place a semantics could still leave a trace, since meaning
lives between a text and a world, not inside the text alone.

- **T6 - the referent question:** text-image covariation first (herbal text vs
  plant-drawing similarity), the direct heir to the negative label test;
  guardrails framed in \`VOYNICH-LAB-PLAN.md\` (section 3, T6). NOT started: an
  image-ingestion subproject, to open with eyes open (the label proxy was
  negative).
- **Deterministic word-grammar induction** (minimum-description-length
  segmentation) if a better slot split becomes necessary; heir to phase T4,
  withdrawn on 2026-06-12 (plan section 3: its proposer role was already filled by
  the session loop, under VOY-DOC-04, which remains in force).
- **Cross-validation by folds** on the working corpus: the preferred instrument
  for discriminating families more finely without using up the frozen held-out
  (now reserved only for final confirmation).
`;

await Bun.write(REPORT_PATH, report);
console.log(`Report written to ${REPORT_PATH}`);
console.log(
  `calibration ${calibrationPassed}/${calibrationChecks.length}, T2 closest: ${t2Ranking[0]?.name}`,
);
console.log(`T3 rows: ${t3RankingRows.length}, frontier rows: ${t3FrontierRows.length}`);
